# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=10000)),
                ('short_description', models.CharField(max_length=999999)),
                ('long_description', models.CharField(max_length=9999999999)),
                ('company_name', models.CharField(max_length=1000)),
                ('company_logo', models.ImageField(upload_to='logo')),
            ],
        ),
    ]
