# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='profession',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
